// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SmFiscalPrinter;

{$R *.RES}
{ITE} {LCID:00000409:00000419} {}
{ITE} {DFMFileType} {Fmu\fmuEMail.dfm}
{ITE} {DFMFileType} {Fmu\fmuLogo.dfm}
{ITE} {DFMFileType} {Fmu\fmuPhone.dfm}
{ITE} {DFMFileType} {Fmu\fmuSelect.dfm}
{ITE} {DFMFileType} {Fmu\fmuTimeSync.dfm}
{ITE} {RCFileType} {SmFiscalPrinter_DRC.rc}

{$R 'Fmu\fmuEMail.dfm' fmEMail:TForm}
{$R 'Fmu\fmuLogo.dfm' fmLogo:TForm}
{$R 'Fmu\fmuPhone.dfm' fmPhone:TForm}
{$R 'Fmu\fmuSelect.dfm' fmSelect:TForm}
{$R 'Fmu\fmuTimeSync.dfm' fmTimeSync:TForm}
{$R 'SmFiscalPrinter_DRC.res' 'SmFiscalPrinter_DRC.rc'}

{$E RUS}

begin
end.