library OposTestTestLib;

uses
  TestFramework,
  GUITestRunner,
  AutoScrollTest in 'Units\AutoScrollTest.pas',
  FileUtils in '..\..\Source\Shared\FileUtils.pas',
  TextDfmTest in 'Units\TextDfmTest.pas',
  SmFiscalPrinterLib_TLB in '..\..\Source\SmFiscalPrinter\SmFiscalPrinterLib_TLB.pas',
  OposScale_1_12_Lib_TLB_Var in '..\..\Source\OposTest\Fmu\OposScale_1_12_Lib_TLB_Var.pas',
  fmuAbout in '..\..\Source\OposTest\Fmu\fmuAbout.pas' {fmAbout},
  fmuCashDrawer in '..\..\Source\OposTest\Fmu\fmuCashDrawer.pas' {fmCashDrawer},
  fmuCashGeneral in '..\..\Source\OposTest\Fmu\fmuCashGeneral.pas' {fmCashGeneral},
  fmuCashWait in '..\..\Source\OposTest\Fmu\fmuCashWait.pas' {fmCashWait},
  fmuFiscalPrinter in '..\..\Source\OposTest\Fmu\fmuFiscalPrinter.pas' {fmFiscalPrinter},
  fmuFptrFiscalStorage in '..\..\Source\OposTest\Fmu\fmuFptrFiscalStorage.pas' {fmFptrFiscalStorage},
  fmuFptrMonitoring in '..\..\Source\OposTest\Fmu\fmuFptrMonitoring.pas' {fmFptrMonitoring},
  fmuFptrDirectIO in '..\..\Source\OposTest\Fmu\fmuFptrDirectIO.pas' {fmFptrDirectIO},
  fmuFptrDirectIOBarcode in '..\..\Source\OposTest\Fmu\fmuFptrDirectIOBarcode.pas' {fmFptrDirectIOBarcode},
  fmuFptrDirectIOEndDay in '..\..\Source\OposTest\Fmu\fmuFptrDirectIOEndDay.pas' {fmFptrDirectIOEndDay},
  fmuFptrDirectIOHex in '..\..\Source\OposTest\Fmu\fmuFptrDirectIOHex.pas' {fmFptrDirectIOHex},
  fmuFptrDirectIOStr in '..\..\Source\OposTest\Fmu\fmuFptrDirectIOStr.pas' {fmFptrDirectIOStr},
  fmuFptrDriverTest in '..\..\Source\OposTest\Fmu\fmuFptrDriverTest.pas' {fmFptrDriverTest},
  fmuFptrFiscalDocument in '..\..\Source\OposTest\Fmu\fmuFptrFiscalDocument.pas' {fmFptrFiscalDocument},
  fmuFptrFiscalReports in '..\..\Source\OposTest\Fmu\fmuFptrFiscalReports.pas' {fmFptrFiscalReports},
  fmuFptrGeneral in '..\..\Source\OposTest\Fmu\fmuFptrGeneral.pas' {fmFptrGeneral},
  fmuFptrGetData in '..\..\Source\OposTest\Fmu\fmuFptrGetData.pas' {fmFptrGetData},
  fmuFptrInfo in '..\..\Source\OposTest\Fmu\fmuFptrInfo.pas' {fmFptrInfo},
  fmuFptrNonFiscal in '..\..\Source\OposTest\Fmu\fmuFptrNonFiscal.pas' {fmFptrNonFiscal},
  fmuFptrProperties in '..\..\Source\OposTest\Fmu\fmuFptrProperties.pas' {fmFptrProperties},
  fmuFptrRecCash in '..\..\Source\OposTest\Fmu\fmuFptrRecCash.pas' {fmFptrRecCash},
  fmuFptrReceipt in '..\..\Source\OposTest\Fmu\fmuFptrReceipt.pas' {fmFptrReceipt},
  fmuFptrReceiptTest in '..\..\Source\OposTest\Fmu\fmuFptrReceiptTest.pas' {fmFptrReceiptTest},
  fmuFptrRecItem in '..\..\Source\OposTest\Fmu\fmuFptrRecItem.pas' {fmFptrRecItem},
  fmuFptrRecItemAdjust in '..\..\Source\OposTest\Fmu\fmuFptrRecItemAdjust.pas' {fmFptrRecItemAdjust},
  fmuFptrRecItemVoid in '..\..\Source\OposTest\Fmu\fmuFptrRecItemVoid.pas' {fmFptrRecItemVoid},
  fmuFptrRecMessage in '..\..\Source\OposTest\Fmu\fmuFptrRecMessage.pas' {fmFptrRecMessage},
  fmuFptrRecNotPaid in '..\..\Source\OposTest\Fmu\fmuFptrRecNotPaid.pas' {fmFptrRecNotPaid},
  fmuFptrRecPackageAdjustment in '..\..\Source\OposTest\Fmu\fmuFptrRecPackageAdjustment.pas' {fmFptrRecPackageAdjustment},
  fmuFptrRecPackageAdjustVoid in '..\..\Source\OposTest\Fmu\fmuFptrRecPackageAdjustVoid.pas' {fmFptrRecPackageAdjustVoid},
  fmuFptrRecRefund in '..\..\Source\OposTest\Fmu\fmuFptrRecRefund.pas' {fmFptrRecRefund},
  fmuFptrRecRefundVoid in '..\..\Source\OposTest\Fmu\fmuFptrRecRefundVoid.pas' {fmFptrRecRefundVoid},
  fmuFptrRecSubtotal in '..\..\Source\OposTest\Fmu\fmuFptrRecSubtotal.pas' {fmFptrRecSubtotal},
  fmuFptrRecSubtotalAdjustment in '..\..\Source\OposTest\Fmu\fmuFptrRecSubtotalAdjustment.pas' {fmFptrRecSubtotalAdjustment},
  fmuFptrRecSubtotalAdjustVoid in '..\..\Source\OposTest\Fmu\fmuFptrRecSubtotalAdjustVoid.pas' {fmFptrRecSubtotalAdjustVoid},
  fmuFptrRecTaxID in '..\..\Source\OposTest\Fmu\fmuFptrRecTaxID.pas' {fmFptrRecTaxID},
  fmuFptrRecTotal in '..\..\Source\OposTest\Fmu\fmuFptrRecTotal.pas' {fmFptrRecTotal},
  fmuFptrStatistics in '..\..\Source\OposTest\Fmu\fmuFptrStatistics.pas' {fmFptrStatistics},
  fmuFptrSetline in '..\..\Source\OposTest\Fmu\fmuFptrSetline.pas' {fmFptrSetLine},
  fmuFptrSetVatTable in '..\..\Source\OposTest\Fmu\fmuFptrSetVatTable.pas' {fmFptrSetVatTable},
  fmuFptrSlipInsertion in '..\..\Source\OposTest\Fmu\fmuFptrSlipInsertion.pas' {fmFptrSlipInsertion},
  fmuFptrTraining in '..\..\Source\OposTest\Fmu\fmuFptrTraining.pas' {fmFptrTraining},
  fmuFptrWritableProperties in '..\..\Source\OposTest\Fmu\fmuFptrWritableProperties.pas' {fmFptrWritableProperties},
  fmuMain in '..\..\Source\OposTest\Fmu\fmuMain.pas' {fmMain},
  fmuPosPrinter in '..\..\Source\OposTest\Fmu\fmuPosPrinter.pas' {fmPosPrinter},
  fmuPrintRecItemRefund in '..\..\Source\OposTest\Fmu\fmuPrintRecItemRefund.pas' {fmPrintRecItemRefund},
  fmuPrintRecItemRefundVoid in '..\..\Source\OposTest\Fmu\fmuPrintRecItemRefundVoid.pas' {fmPrintRecItemRefundVoid},
  fmuPrintRecVoidItem in '..\..\Source\OposTest\Fmu\fmuPrintRecVoidItem.pas' {fmPrintRecVoidItem},
  fmuPtrGeneral in '..\..\Source\OposTest\Fmu\fmuPtrGeneral.pas' {fmPtrGeneral},
  untUtil in '..\..\Source\OposTest\Units\untUtil.pas',
  AlignStrings in '..\..\Source\OposTest\Units\AlignStrings.pas',
  DIODescription in '..\..\Source\OposTest\Units\DIODescription.pas',
  DriverTest in '..\..\Source\OposTest\Units\DriverTest.pas',
  OPOSDate in '..\..\Source\OposTest\Units\OPOSDate.pas',
  PrinterTest in '..\..\Source\OposTest\Units\PrinterTest.pas',
  untPages in '..\..\Source\OposTest\Units\untPages.pas',
  OposCashDrawer in '..\..\Source\Opos\OposCashDrawer.pas',
  Opos in '..\..\Source\Opos\Opos.pas',
  OposUtils in '..\..\Source\Opos\OposUtils.pas',
  Oposhi in '..\..\Source\Opos\Oposhi.pas',
  OPOSException in '..\..\Source\Opos\OposException.pas',
  OposCash in '..\..\Source\Opos\OposCash.pas',
  OposFptrUtils in '..\..\Source\Opos\OposFptrUtils.pas',
  OposFptr in '..\..\Source\Opos\OposFptr.pas',
  OposFptrhi in '..\..\Source\Opos\OposFptrhi.pas',
  VersionInfo in '..\..\Source\Shared\VersionInfo.pas',
  OposDevice in '..\..\Source\Opos\OposDevice.pas',
  DirectIOAPI in '..\..\Source\SmFiscalPrinter\Units\DirectIOAPI.pas',
  CommandDef in '..\..\Source\SmScale\Units\CommandDef.pas',
  XMLParser in '..\..\Source\Shared\XMLParser.pas',
  CommandParam in '..\..\Source\SmScale\Units\CommandParam.pas',
  PrinterCommand in '..\..\Source\SmFiscalPrinter\Units\PrinterCommand.pas',
  PrinterTypes in '..\..\Source\SmFiscalPrinter\Units\PrinterTypes.pas',
  BinStream in '..\..\Source\SmScale\Units\BinStream.pas',
  LogFile in '..\..\Source\Shared\LogFile.pas',
  DebugUtils in '..\..\Source\Shared\DebugUtils.pas',
  OposPosPrinter in '..\..\Source\Opos\OposPosPrinter.pas',
  OposPtrUtils in '..\..\Source\Opos\OposPtrUtils.pas',
  OposPtr in '..\..\Source\Opos\OposPtr.pas',
  OposPtrhi in '..\..\Source\Opos\OposPtrhi.pas',
  OposScalUtils in '..\..\Source\Opos\OposScalUtils.pas',
  OposScal in '..\..\Source\Opos\OposScal.pas',
  BStrUtil in '..\..\Source\Shared\BStrUtil.pas',
  OposFiscalPrinter in '..\..\Source\Opos\OposFiscalPrinter.pas',
  NCRCashDrawer in '..\..\Source\Opos\NCRCashDrawer.pas',
  PrinterEncoding in '..\..\Source\Opos\PrinterEncoding.pas',
  PayType in '..\..\Source\SmFiscalPrinter\Units\PayType.pas',
  OposCashDrawerIntf in '..\..\Source\Opos\OposCashDrawerIntf.pas',
  SMCashDrawer in '..\..\Source\Opos\SMCashDrawer.pas',
  NCRCashDrawer_TLB in '..\..\Source\Opos\NCRCashDrawer_TLB.pas',
  BaseForm in '..\..\Source\Shared\BaseForm.pas',
  PrinterParametersIni in '..\..\Source\SmFiscalPrinter\Units\PrinterParametersIni.pas',
  PrinterParameters in '..\..\Source\SmFiscalPrinter\Units\PrinterParameters.pas',
  SmIniFile in '..\..\Source\SmFiscalPrinter\Units\SmIniFile.pas',
  PrinterParametersX in '..\..\Source\SmFiscalPrinter\Units\PrinterParametersX.pas',
  PrinterParametersRegIBT in '..\..\Source\SmFiscalPrinter\Units\PrinterParametersRegIBT.pas',
  fmuFptrSetHeaderTrailer in '..\..\Source\OposTest\Fmu\fmuFptrSetHeaderTrailer.pas' {fmFptrSetHeaderTrailer},
  PrinterParametersReg in '..\..\Source\SmFiscalPrinter\Units\PrinterParametersReg.pas',
  StringUtils in '..\..\Source\Shared\StringUtils.pas',
  OposScalhi in '..\..\Source\Opos\OposScalhi.pas',
  fmuScale in '..\..\Source\OposTest\Fmu\fmuScale.pas' {fmScale},
  OposScale in '..\..\Source\OposTest\Units\OposScale.pas',
  OposScale_1_13_Lib_TLB in '..\..\Source\Opos\OposScale_1_13_Lib_TLB.pas',
  fmuScaleGeneral in '..\..\Source\OposTest\Fmu\fmuScaleGeneral.pas' {fmScaleGeneral},
  fmuScaleMain in '..\..\Source\OposTest\Fmu\fmuScaleMain.pas' {fmScaleMain},
  fmuScaleProperties in '..\..\Source\OposTest\Fmu\fmuScaleProperties.pas' {fmScaleProperties},
  fmuScaleHealth in '..\..\Source\OposTest\Fmu\fmuScaleHealth.pas' {fmScaleHealth},
  BStdUtil in '..\..\Source\Shared\BStdUtil.pas',
  fmuFptrDate in '..\..\Source\OposTest\Fmu\fmuFptrDate.pas' {fmFptrDate},
  fmuFptrEvents in '..\..\Source\OposTest\Fmu\fmuFptrEvents.pas' {fmFptrEvents},
  SMFiscalPrinter in '..\..\Source\Opos\SMFiscalPrinter.pas',
  OposFiscalPrinter_1_12_Lib_TLB in '..\..\Source\Opos\OposFiscalPrinter_1_12_Lib_TLB.pas',
  OposFiscalPrinter_1_13_Lib_TLB in '..\..\Source\Opos\OposFiscalPrinter_1_13_Lib_TLB.pas',
  fmuMalina in '..\..\Source\OposTest\Fmu\fmuMalina.pas' {fmMalina},
  fmuTextBlock in '..\..\Source\OposTest\Fmu\fmuTextBlock.pas' {fmTextBlock},
  fmuTextreceipt in '..\..\Source\OposTest\Fmu\fmuTextReceipt.pas' {fmTextReceipt},
  fmuTankReport in '..\..\Source\OposTest\Fmu\fmuTankReport.pas' {fmTankReport},
  fmuFptrFroudReceipt in '..\..\Source\OposTest\Fmu\fmuFptrFroudReceipt.pas' {fmFptrFroudReceipt},
  MalinaCard in '..\..\Source\SmFiscalPrinter\Units\MalinaCard.pas',
  UniposReader in '..\..\Source\SmFiscalPrinter\Units\UniposReader.pas',
  TankReader in '..\..\Source\SmFiscalPrinter\Units\TankReader.pas',
  UniposTank in '..\..\Source\SmFiscalPrinter\Units\UniposTank.pas',
  NotifyThread in '..\..\Source\Shared\NotifyThread.pas',
  fmuFptrTest in '..\..\Source\OposTest\Fmu\fmuFptrTest.pas' {fmFptrTest},
  fmuFptrAddHeaderTrailer in '..\..\Source\OposTest\Fmu\fmuFptrAddHeaderTrailer.pas' {fmFptrAddHeaderTrailer},
  fmuFptrThreadTest in '..\..\Source\OposTest\Fmu\fmuFptrThreadTest.pas' {fmFptrThreadTest},
  fmuFptrTest2 in '..\..\Source\OposTest\Fmu\fmuFptrTest2.pas' {fmFptrTest2},
  VatCode in '..\..\Source\SmFiscalPrinter\Units\VatCode.pas';

{$R *.RES}

exports
  RegisteredTests name 'Test';
end.
