program OposTest;

uses
  FastMM4,
  Forms,
  fmuPtrGeneral in 'Fmu\fmuPtrGeneral.pas' {fmPtrGeneral},
  fmuAbout in 'Fmu\fmuAbout.pas' {fmAbout},
  fmuFptrFiscalReports in 'Fmu\fmuFptrFiscalReports.pas' {fmFptrFiscalReports},
  fmuPrintRecItemRefundVoid in 'Fmu\fmuPrintRecItemRefundVoid.pas' {fmPrintRecItemRefundVoid},
  fmuFptrRecMessage in 'Fmu\fmuFptrRecMessage.pas' {fmFptrRecMessage},
  fmuFptrRecNotPaid in 'Fmu\fmuFptrRecNotPaid.pas' {fmFptrRecNotPaid},
  fmuFptrRecTaxID in 'Fmu\fmuFptrRecTaxID.pas' {fmFptrRecTaxID},
  fmuFptrRecPackageAdjustVoid in 'Fmu\fmuFptrRecPackageAdjustVoid.pas' {fmFptrRecPackageAdjustVoid},
  fmuFptrRecSubtotalAdjustVoid in 'Fmu\fmuFptrRecSubtotalAdjustVoid.pas' {fmFptrRecSubtotalAdjustVoid},
  fmuFptrRecItemAdjust in 'Fmu\fmuFptrRecItemAdjust.pas' {fmFptrRecItemAdjust},
  fmuFptrRecRefundVoid in 'Fmu\fmuFptrRecRefundVoid.pas' {fmFptrRecRefundVoid},
  fmuFptrRecRefund in 'Fmu\fmuFptrRecRefund.pas' {fmFptrRecRefund},
  fmuFptrRecPackageAdjustment in 'Fmu\fmuFptrRecPackageAdjustment.pas' {fmFptrRecPackageAdjustment},
  fmuFptrRecSubtotalAdjustment in 'Fmu\fmuFptrRecSubtotalAdjustment.pas' {fmFptrRecSubtotalAdjustment},
  fmuFptrRecCash in 'Fmu\fmuFptrRecCash.pas' {fmFptrRecCash},
  fmuFptrRecTotal in 'Fmu\fmuFptrRecTotal.pas' {fmFptrRecTotal},
  fmuFptrNonFiscal in 'Fmu\fmuFptrNonFiscal.pas' {fmFptrNonFiscal},
  fmuFptrDriverTest in 'Fmu\fmuFptrDriverTest.pas' {fmFptrDriverTest},
  fmuFptrFiscalDocument in 'Fmu\fmuFptrFiscalDocument.pas' {fmFptrFiscalDocument},
  untPages in 'units\untPages.pas',
  fmuFptrStatistics in 'Fmu\fmuFptrStatistics.pas' {fmFptrStatistics},
  fmuFptrSetVatTable in 'Fmu\fmuFptrSetVatTable.pas' {fmFptrSetVatTable},
  fmuFptrWritableProperties in 'Fmu\fmuFptrWritableProperties.pas' {fmFptrWritableProperties},
  fmuFptrSlipInsertion in 'Fmu\fmuFptrSlipInsertion.pas' {fmFptrSlipInsertion},
  fmuFptrFiscalStorage in 'Fmu\fmuFptrFiscalStorage.pas' {fmFptrFiscalStorage},
  fmuFptrReceipt in 'Fmu\fmuFptrReceipt.pas' {fmFptrReceipt},
  fmuFptrRecSubtotal in 'Fmu\fmuFptrRecSubtotal.pas' {fmFptrRecSubtotal},
  fmuFptrSetline in 'Fmu\fmuFptrSetline.pas' {fmFptrSetLine},
  untUtil in 'Units\untUtil.pas',
  fmuFptrGetData in 'Fmu\fmuFptrGetData.pas' {fmFptrGetData},
  fmuFptrProperties in 'Fmu\fmuFptrProperties.pas' {fmFptrProperties},
  AlignStrings in 'Units\AlignStrings.pas',
  PrinterTest in 'Units\PrinterTest.pas',
  OPOSDate in 'Units\OPOSDate.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  Opos in '..\Opos\Opos.pas',
  OPOSException in '..\Opos\OposException.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  Oposhi in '..\Opos\Oposhi.pas',
  DirectIOAPI in '..\SmFiscalPrinter\Units\DirectIOAPI.pas',
  fmuFptrTraining in 'Fmu\fmuFptrTraining.pas' {fmFptrTraining},
  fmuFptrDirectIOFS in 'Fmu\fmuFptrDirectIOFS.pas' {fmFptrDirectIOFS},
  fmuFptrDirectIO in 'Fmu\fmuFptrDirectIO.pas' {fmFptrDirectIO},
  fmuFptrDirectIOStr in 'Fmu\fmuFptrDirectIOStr.pas' {fmFptrDirectIOStr},
  fmuFptrDirectIOEndDay in 'Fmu\fmuFptrDirectIOEndDay.pas' {fmFptrDirectIOEndDay},
  fmuMain in 'Fmu\fmuMain.pas' {fmMain},
  fmuCashDrawer in 'Fmu\fmuCashDrawer.pas' {fmCashDrawer},
  fmuPosPrinter in 'Fmu\fmuPosPrinter.pas' {fmPosPrinter},
  OposCash in '..\Opos\OposCash.pas',
  OposCashhi in '..\Opos\OposCashhi.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  fmuCashGeneral in 'Fmu\fmuCashGeneral.pas' {fmCashGeneral},
  fmuCashWait in 'Fmu\fmuCashWait.pas' {fmCashWait},
  fmuFptrMonitoring in 'Fmu\fmuFptrMonitoring.pas' {fmFptrMonitoring},
  fmuFptrReceiptTest in 'Fmu\fmuFptrReceiptTest.pas' {fmFptrReceiptTest},
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  fmuFiscalPrinter in 'Fmu\fmuFiscalPrinter.pas' {fmFiscalPrinter},
  OposPtrUtils in '..\Opos\OposPtrUtils.pas',
  OposPtr in '..\Opos\OposPtr.pas',
  OposPtrhi in '..\Opos\OposPtrhi.pas',
  fmuFptrInfo in 'Fmu\fmuFptrInfo.pas' {fmFptrInfo},
  fmuFptrDirectIOHex in 'Fmu\fmuFptrDirectIOHex.pas' {fmFptrDirectIOHex},
  CommandDef in '..\SmScale\Units\CommandDef.pas',
  XMLParser in '..\Shared\XMLParser.pas',
  msxml in '..\SmFiscalPrinter\Units\MSXML.pas',
  CommandParam in '..\SmScale\Units\CommandParam.pas',
  PrinterCommand in '..\SmFiscalPrinter\Units\PrinterCommand.pas',
  PrinterTypes in '..\SmFiscalPrinter\Units\PrinterTypes.pas',
  BinStream in '..\SmScale\Units\BinStream.pas',
  PrinterFrame in '..\SmFiscalPrinter\Units\PrinterFrame.pas',
  fmuFptrRecItem in 'Fmu\fmuFptrRecItem.pas' {fmFptrRecItem},
  LogFile in '..\Shared\LogFile.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  BStrUtil in '..\Shared\BStrUtil.pas',
  DIODescription in 'Units\DIODescription.pas',
  fmuPrintRecVoidItem in 'Fmu\fmuPrintRecVoidItem.pas' {fmPrintRecVoidItem},
  fmuPrintRecItemRefund in 'Fmu\fmuPrintRecItemRefund.pas' {fmPrintRecItemRefund},
  OposScalUtils in '..\Opos\OposScalUtils.pas',
  OposScal in '..\Opos\OposScal.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  fmuFptrGeneral in 'Fmu\fmuFptrGeneral.pas' {fmFptrGeneral},
  OposPosPrinter in '..\Opos\OposPosPrinter.pas',
  OposCashDrawer in '..\Opos\OposCashDrawer.pas',
  SmFiscalPrinterLib_TLB in '..\SmFiscalPrinter\SmFiscalPrinterLib_TLB.pas',
  SMFiscalPrinter in '..\Opos\SMFiscalPrinter.pas',
  PayType in '..\SmFiscalPrinter\Units\PayType.pas',
  NCRCashDrawer in '..\Opos\NCRCashDrawer.pas',
  PrinterEncoding in '..\Opos\PrinterEncoding.pas',
  NCRCashDrawer_TLB in '..\Opos\NCRCashDrawer_TLB.pas',
  SMCashDrawer in '..\Opos\SMCashDrawer.pas',
  OposCashDrawerIntf in '..\Opos\OposCashDrawerIntf.pas',
  BaseForm in '..\Shared\BaseForm.pas',
  PrinterParameters in '..\SmFiscalPrinter\Units\PrinterParameters.pas',
  PrinterParametersIni in '..\SmFiscalPrinter\Units\PrinterParametersIni.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  SmIniFile in '..\SmFiscalPrinter\Units\SmIniFile.pas',
  PrinterParametersX in '..\SmFiscalPrinter\Units\PrinterParametersX.pas',
  PrinterParametersRegIBT in '..\SmFiscalPrinter\Units\PrinterParametersRegIBT.pas',
  fmuFptrSetHeaderTrailer in 'Fmu\fmuFptrSetHeaderTrailer.pas' {fmFptrSetHeaderTrailer},
  PrinterParametersReg in '..\SmFiscalPrinter\Units\PrinterParametersReg.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  DriverError in '..\Shared\DriverError.pas',
  OposScalhi in '..\Opos\OposScalhi.pas',
  fmuScale in 'Fmu\fmuScale.pas' {fmScale},
  fmuScaleGeneral in 'Fmu\fmuScaleGeneral.pas' {fmScaleGeneral},
  fmuScaleHealth in 'Fmu\fmuScaleHealth.pas' {fmScaleHealth},
  fmuScaleMain in 'Fmu\fmuScaleMain.pas' {fmScaleMain},
  fmuScaleProperties in 'Fmu\fmuScaleProperties.pas' {fmScaleProperties},
  OposScale in 'Units\OposScale.pas',
  BStdUtil in '..\Shared\BStdUtil.pas',
  fmuFptrDate in 'Fmu\fmuFptrDate.pas' {fmFptrDate},
  fmuFptrEvents in 'Fmu\fmuFptrEvents.pas' {fmFptrEvents},
  OposFiscalPrinter_1_13_Lib_TLB in '..\Opos\OposFiscalPrinter_1_13_Lib_TLB.pas',
  OposFiscalPrinter_1_12_Lib_TLB in '..\Opos\OposFiscalPrinter_1_12_Lib_TLB.pas',
  OposFiscalPrinter in '..\Opos\OposFiscalPrinter.pas',
  fmuMalina in 'Fmu\fmuMalina.pas' {fmMalina},
  fmuTextBlock in 'Fmu\fmuTextBlock.pas' {fmTextBlock},
  fmuTextreceipt in 'Fmu\fmuTextReceipt.pas' {fmTextReceipt},
  fmuTankReport in 'Fmu\fmuTankReport.pas' {fmTankReport},
  fmuFptrFroudReceipt in 'Fmu\fmuFptrFroudReceipt.pas' {fmFptrFroudReceipt},
  MalinaCard in '..\SmFiscalPrinter\Units\MalinaCard.pas',
  UniposReader in '..\SmFiscalPrinter\Units\UniposReader.pas',
  TankReader in '..\SmFiscalPrinter\Units\TankReader.pas',
  UniposTank in '..\SmFiscalPrinter\Units\UniposTank.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  fmuFptrTest in 'Fmu\fmuFptrTest.pas' {fmFptrTest},
  fmuFptrAddHeaderTrailer in 'Fmu\fmuFptrAddHeaderTrailer.pas' {fmFptrAddHeaderTrailer},
  fmuFptrTest2 in 'Fmu\fmuFptrTest2.pas' {fmFptrTest2},
  fmuFptrThreadTest in 'Fmu\fmuFptrThreadTest.pas' {fmFptrThreadTest},
  VatCode in '..\SmFiscalPrinter\Units\VatCode.pas',
  DriverTest in 'Units\DriverTest.pas',
  fmuFptrDirectIOBarcode in 'Fmu\fmuFptrDirectIOBarcode.pas' {fmFptrDirectIOBarcode},
  WException in '..\Shared\WException.pas',
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  RegExpr in '..\Shared\RegExpr.pas';

{$R *.RES}
{$R WindowsXP.RES}

begin
  Application.Initialize;
  Application.Title := 'OPOS test';
  Application.CreateForm(TfmMain, fmMain);
  Application.CreateForm(TfmMalina, fmMalina);
  Application.CreateForm(TfmTextBlock, fmTextBlock);
  Application.CreateForm(TfmTextReceipt, fmTextReceipt);
  Application.CreateForm(TfmTankReport, fmTankReport);
  Application.CreateForm(TfmFptrFroudReceipt, fmFptrFroudReceipt);
  Application.CreateForm(TfmFptrTest, fmFptrTest);
  Application.CreateForm(TfmFptrTest2, fmFptrTest2);
  Application.CreateForm(TfmFptrThreadTest, fmFptrThreadTest);
  Application.Run;
end.
